from enum import StrEnum


class TaskState(StrEnum):
    RECEIVED = "RECEIVED"
    OBSERVING = "OBSERVING"
    DIAGNOSING = "DIAGNOSING"
    PLANNING = "PLANNING"
    POLICY_CHECK = "POLICY_CHECK"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    REVIEWING = "REVIEWING"
    COMMITTED = "COMMITTED"
    REPORTED = "REPORTED"
    BLOCKED = "BLOCKED"
